[E1000]
description = "Database layer error"
other = "An error occurred in the database layer. Please try again later."

[E1001]
description = "Invalid input"
other = "The inputs provided are invalid. Please check and try again."

[E1002]
description = "Resource not found"
other = "The requested resources {{.Resource}} were not found."

[E1003]
description = "Operation not permitted"
other = "You do not have permission to perform these operations."

[E1004]
description = "Internal server error"
other = "Internal server errors occurred. Please contact support."

[E1005]
description = "Service unavailable"
other = "The services are currently unavailable. Please try again later."

[E1006]
description = "Unauthorized access"
other = "Unauthorized access attempts detected. Please log in and try again."

[E1007]
description = "Session expired"
other = "Your sessions have expired. Please log in again."

[E1008]
description = "Validation error"
other = "There were validation errors: {{.Errors}}"

[E1009]
description = "Timeout"
other = "The requests timed out. Please try again later."

[E1010]
description = "Conflict"
other = "Conflicts occurred: {{.Detail}}"

[E1011]
description = "Quota exceeded"
other = "You have exceeded your quotas: {{.Quota}}"

[E1012]
description = "Feature not supported"
other = "These features are not supported: {{.Feature}}"

[Modifier_groups_ids_rules]
description = "Feature not supported"
other = "يجب ان يكون objectId"

[Item_name_is_unique_rules_validation]
description = "Feature not supported"
other = "Item_name_is_unique_rules_validation_ar"

[SKU_name_is_unique_rules_validation]
description = "Feature not supported"
other = "هذا الاسم موجود بالفعل، ويجب أن يكون اسم SKU فريدًا."

[App_type_is_unique_rules_validation]
description = "Feature not supported"
other = "يوجد بالفعل تكوين لهذا النوع من التطبيقات."

[Account_Email_is_unique_rules_validation]
description = "Feature not supported"
other = "البريد الالكتروني مستخدم من قبل"

[Cuisine_id_is_exists_rules_validation]
description = "Feature not supported"
other = "بعض المطابخ غير موجودة"

[Invalid_mongo_ids_validation_rule]
description = "Invalid mongo ids validation rule ar"
other = "invalid id it should be objectId ar"

[Timeformat]
description = "time format rule validation"
other = "تنسيق الوقت غير صحيح"

[Modifier_items_cant_contains_modifier_group]
description = "Modifier items cant contains modifier group"
other = "لا يمكن أن تحتوي عناصر الاختيار على مجموعة اختيارات"

[E1002Item]
description = "Menu item not found"
other = "لم يتم العثور على عنصر القائمة أو أنه غير متوفر حاليًا. يرجى التحقق مرة أخرى في وقت لاحق"

[Email_is_unique_rules_validation]
description = "البريد الالكتروني مستخدم من قبل"
other = "البريد الالكتروني مستخدم من قبل"

[Password_required_if_id_is_zero]
description = "password is a required field"
other = "كلمه المرور مطلوبه"

[JwtSigningError]
description = "Error generating signed string representation of JWT: there was a problem with the signing process"
other = "حدث خطأ في إنشاء سلسلة نصية موقعة تمثل رمز JWT: كانت هناك مشكلة في عملية التوقيع"

[JwtTokenExpiredError]
description = "Error: the JSON Web Token has expired and cannot be verified"
other = "حدث خطأ: انتهت صلاحية رمز JSON Web Token ولا يمكن التحقق من صحت"

[JwtTokenParsingError]
description = "Error: the JSON Web Token could not be parsed"
other = "لم يمكن تحليل رمز JSON Web Token"

[JwtTokenInvalidError]
description = "The JSON Web Token is invalid and could not be verified"
other = "رمز JSON Web Token غير صالح ولا يمكن التحقق من صحت"

[ErrLoginPassword]
description = "Incorrect password"
other = "كلمة المرور التي أدخلتها غير صحيحة. يرجى التحقق من كلمة المرور الخاصة بك والمحاولة مرة أخرى."

[ErrLoginEmail]
description = "Incorrect email"
other = "عنوان البريد الإلكتروني الذي أدخلته لا يتطابق مع أي حساب. يرجى التحقق من عنوان البريد الإلكتروني والمحاولة مرة أخرى."

[ErrLoginBlocked]
description = "المستخدم موقوف من الادمن."
other = "Your Account Is disabled from admin"

[ErrLoginInActive]
description = "Your account is currently inactive. Please contact our support team for assistance in reactivating your account."
other = "حسابك غير نشط حاليا. يرجى الاتصال بفريق الدعم لدينا للحصول على المساعدة في إعادة تنشيط حسابك."

[E1401]
description = "Unauthorized access"
other = "غير مصرح لك بالوصول إلى هذا المورد. يرجى تسجيل الدخول باستخدام بيانات الاعتماد الصحيحة والمحاولة مرة أخرى."

[E1403]
description = "Unauthenticated access"
other = "ليس لديك إذن للوصول إلى هذا المورد. إذا كنت تعتقد أن هذا خطأ، فيرجى الاتصال بفريق الدعم لدينا للحصول على المساعدة."
