[E1000]
description = "Database layer error"
other = "An error occurred in the database layer. Please try again later."

[E1001]
description = "Invalid input"
other = "The inputs provided are invalid. Please check and try again."

[E1002]
description = "Resource not found"
other = "The requested resources were not found."

[E1003]
description = "Operation not permitted"
other = "You do not have permission to perform these operations."

[E1004]
description = "Internal server error"
other = "Internal server errors occurred. Please contact support."

[E1005]
description = "Service unavailable"
other = "The services are currently unavailable. Please try again later."

[E1006]
description = "Unauthorized access"
other = "Unauthorized access attempts detected. Please log in and try again."

[E1007]
description = "Session expired"
other = "Your sessions have expired. Please log in again."

[E1008]
description = "Validation error"
other = "There were validation errors: {{.Errors}}"

[E1009]
description = "Timeout"
other = "The requests timed out. Please try again later."

[E1010]
description = "Conflict"
other = "Conflicts occurred: {{.Detail}}"

[E1011]
description = "Quota exceeded"
other = "You have exceeded your quotas: {{.Quota}}"

[E1012]
description = "Feature not supported"
other = "These features are not supported: {{.Feature}}"

[Modifier_groups_ids_rules_validation]
description = "Feature not supported"
other = "These features are not supported: {{.Feature}}"

[Item_name_is_unique_rules_validation]
description = "Feature not supported"
other = "Item_name_is_unique_rules_validation"

[Account_Email_is_unique_rules_validation]
description = "Email is Unique"
other = "Email is Exists"

[Timeformat]
description = "time format rule validation"
other = "time format is not valid"

[Invalid_mongo_ids_validation_rule]
description = "Invalid mongo ids validation rule"
other = "invalid id it should be objectId"

