[E1000]
description = "Database layer error"
other = "An error occurred in the database layer. Please try again later."

[E1001]
description = "Invalid input"
other = "The inputs provided are invalid. Please check and try again."

[E1002]
description = "Resource not found"
other = "The requested resources were not found."

[E1003]
description = "Operation not permitted"
other = "You do not have permission to perform these operations."

[E1004]
description = "Internal server error"
other = "Internal server errors occurred. Please contact support."

[E1005]
description = "Service unavailable"
other = "The services are currently unavailable. Please try again later."

[E1006]
description = "Unauthorized access"
other = "Unauthorized access attempts detected. Please log in and try again."

[E1007]
description = "Session expired"
other = "Your sessions have expired. Please log in again."

[E1008]
description = "Validation error"
other = "There were validation errors: {{.Errors}}"

[E1009]
description = "Timeout"
other = "The requests timed out. Please try again later."

[E1010]
description = "Conflict"
other = "Conflicts occurred: {{.Detail}}"

[E1011]
description = "Quota exceeded"
other = "You have exceeded your quotas: {{.Quota}}"

[E1012]
description = "Feature not supported"
other = "These features are not supported: {{.Feature}}"

[E1013]
description = "Invalid OTP"
other = "The OTP provided is invalid. Please check and try again."

[E1014]
description = "OTP has expired"
other = "The OTP has expired. Please request a new OTP."

[E1015]
description = "Exceeded maximum OTP trials"
other = "You have exceeded the maximum number of OTP trials for today. Please try again tomorrow."


[Modifier_groups_ids_rules_validation]
description = "Feature not supported"
other = "These features are not supported: {{.Feature}}"

[Item_name_is_unique_rules_validation]
description = "Feature not supported"
other = "Item_name_is_unique_rules_validation"

[SKU_name_is_unique_rules_validation]
description = "Feature not supported"
other = "This name is already exists, SKU name must be unique."

[App_type_is_unique_rules_validation]
description = "Feature not supported"
other = "There is already config exists for this app type."

[Account_Email_is_unique_rules_validation]
description = "Email is Unique"
other = "Email is Exists"

[Cuisine_id_is_exists_rules_validation]
description = "Cuisine Id Not Exist"
other = "Cuisine Not Exist"

[Timeformat]
description = "time format rule validation"
other = "time format is not valid"

[Invalid_mongo_ids_validation_rule]
description = "Invalid mongo ids validation rule"
other = "invalid id it should be objectId"

[Modifier_items_cant_contains_modifier_group]
description = "Modifier items cant contains modifier group"
other = "Modifier items cant contains modifier group"

[E1002Item]
description = "Menu item not found"
other = "The menu item was not found or is currently unavailable. Please check back later."

[Email_is_unique_rules_validation]
description = "Email is Unique"
other = "Email is Exists"

[Password_required_if_id_is_zero]
description = "password is a required field"
other = "password is a required field"

[PhoneNumber_rule_validation]
description = "PhoneNumber is Wrong"
other = "PhoneNumber is Wrong"

[Mobile_location_not_available_error]
description = "mobile_location_not_available_error"
other = "The location is not ready to receive orders now, try later please"