package consts

const REDIRECT_HOME = "home"
const REDIRECT_LOCATION = "location"

const TYPE_PUBLIC = "public"
const TYPE_PRIVATE = "private"

// Events
const SEND_NOTIFICATION = "NOTIFICATION::SEND_NOTIFICATION"

const (
	ORDER_PENDING      = "ORDER_PENDING"
	ORDER_ACCEPTED     = "ORDER_ACCEPTED"
	ORDER_ARRIVED      = "ORDER_ARRIVED"
	ORDER_READY_PICKUP = "ORDER_READY_PICKUP"
	ORDER_PICKUP       = "ORDER_PICKUP"
	ORDER_NOSHOW       = "ORDER_NOSHOW"
	ORDER_CANCELLED    = "ORDER_CANCELLED"
	ORDER_REJECTED     = "ORDER_REJECTED"
	ORDER_TIMEOUT      = "ORDER_TIMEOUT"
)
