package consts

const DEFAULT_PREP_TIME = 15

const LOCATION_PAUSED_STATUS = "PAUSED"
const LOCATION_ONLINE_STATUS = "ONLINE"

const LOCATION_REGISTER_STATUS = "register"
const LOCATION_ACTIVE_STATUS = "active"
const LOCATION_INACTIVE_STATUS = "inactive"

const MENU_SNOOZE_STATUS = "snooze"
const MENU_UNSNOOZE_STATUS = "unsnooze"
